// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package sqlc

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateBoard(ctx context.Context, name string) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :execrows
WITH deleted_tasks AS (
    DELETE FROM tasks
    WHERE column_id IN (SELECT id FROM columns WHERE board_id = $1)
),
deleted_columns AS (
    DELETE FROM columns WHERE board_id = $1
)
DELETE FROM boards
WHERE boards.id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBoard = `-- name: GetBoard :one
SELECT id, name, created_at, updated_at FROM boards
WHERE id = $1
`

func (q *Queries) GetBoard(ctx context.Context, id int32) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoards = `-- name: ListBoards :many
SELECT id, name, created_at, updated_at FROM boards
ORDER BY created_at
`

func (q *Queries) ListBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateBoardParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard, arg.ID, arg.Name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
