// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: column.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (board_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, board_id, name, position, created_at
`

type CreateColumnParams struct {
	BoardID  uuid.UUID `json:"board_id"`
	Name     string    `json:"name"`
	Position int32     `json:"position"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, createColumn, arg.BoardID, arg.Name, arg.Position)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteColumn = `-- name: DeleteColumn :execrows
DELETE FROM columns
WHERE id = $1
`

func (q *Queries) DeleteColumn(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteColumn, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getColumn = `-- name: GetColumn :one
SELECT id, board_id, name, position, created_at FROM columns
WHERE id = $1
`

func (q *Queries) GetColumn(ctx context.Context, id uuid.UUID) (Column, error) {
	row := q.db.QueryRow(ctx, getColumn, id)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listColumnsByBoard = `-- name: ListColumnsByBoard :many
SELECT id, board_id, name, position, created_at FROM columns
WHERE board_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListColumnsByBoard(ctx context.Context, boardID uuid.UUID) ([]Column, error) {
	rows, err := q.db.Query(ctx, listColumnsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Column{}
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns
SET name = $2, position = $3
WHERE id = $1
RETURNING id, board_id, name, position, created_at
`

type UpdateColumnParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Position int32     `json:"position"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, updateColumn, arg.ID, arg.Name, arg.Position)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
